apps/auth_accounts/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    ##-------------Authentication Urls -------------
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    url(r'signup/', SignUp.as_view(),name='signup'),

    ##------------password related urls ----------------
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done'),
        ),
        name='password_reset'),

    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html',
        success_url = reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'),

    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
        ),
        name='password_reset_complete'),

    ##--------------------profile related urls--------------
    url(r'^update_profile/(?P<pk>[\d]+)/$',
        UpdateProfile.as_view(), name='profile_update'),

    url(r'change_avatar/(?P<pk>[\d]+)/$',
        ChangeAvatar.as_view(),
        name='avatar_change')
]

apps/homes/urls.py
from django.conf.urls import url
from .views import *

####---url patterns for calling redirecting to different views with associated namespaces--####

urlpatterns = [
    url(r'^listing/', HomesListing.as_view(), name='listing'),

    url(r'^addcreate', AddCreate.as_view(), name='adcreate'),

    url(r'^homedetail/(?P<slug>[\w-]+)/$', HomeDetail.as_view(),
        name='home_detail'),

    url(r'^update/(?P<slug>[\w-]+)/$', HomeUpdate.as_view(),
        name='home_update'),

    url(r'^like_homes/', LikeHomes.as_view(), name='like_homes'),

    url(r'^favourites/', FavouriteHomes.as_view(),
        name='fav_homes'),

    url(r'^myposts/', MyPosts.as_view(), name='my_posts'),

    url(r'^search/', SearchHomes.as_view(), name='home_search'),

    url(r'^myaccount/(?P<pk>[\w-]+)>', MyAccount.as_view(),
        name='my_account'),

    url(r'makepaymet/(?P<pk>[\d]+)/$', MakePayment.as_view(),
        name='payment'),
]

listinghomes/urls.py
"""
    list of project urls

"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from listinghomes import settings
from apps.homes.views import homelist


urlpatterns = [

    ###########---------------Urls for apps and redirects-----------#########

    url(r'^$', homelist, name="redirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^homes/', include('apps.homes.urls', namespace='homes')),
    url(r'^accounts/', include('apps.auth_accounts.urls', namespace='accounts')),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),




    ###########---------------Urls for password reset and upates-----------#########

    url(r'^settings/password/$',
        auth_views.PasswordChangeView.as_view(
        template_name='password_change.html'),
        name='password_change'),


    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
        name='password_change_done'),
]

 ###########---------------Urls for loading media and static files-----------#########

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/auth_accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    first_name = models.CharField(max_length=75, null=True)
    last_name = models.CharField(max_length=75, null=True)
    contact_number = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    avatar = models.ImageField(upload_to='avatars', blank=True, null=True)

    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            profile, created = UserProfile.objects.get_or_create(user=instance)

    post_save.connect(create_user_profile, sender=User)

    def __unicode__(self):
        return self.user.username

    class Meta:
        verbose_name = "profile"
        verbose_name_plural = "profiles"

apps/auth_accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import FileInput
from apps.auth_accounts.models import UserProfile
from PIL import Image



class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class PhotoForm(forms.ModelForm):
    x_value=forms.FloatField(widget=forms.HiddenInput())
    y_value=forms.FloatField(widget=forms.HiddenInput())
    width=forms.FloatField(widget=forms.HiddenInput())
    height=forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model=UserProfile
        fields=['x_value','y_value','width','height','avatar']

    def save(self):
        photo=super(PhotoForm, self).save()
        x_value=self.cleaned_data.get('x_value')
        print("xvalue",x_value)
        y_value=self.cleaned_data.get('y_value')
        print("yvalue",y_value)
        width=self.cleaned_data.get('width')
        print("width",width)
        height=self.cleaned_data.get('height')
        print("height",height)

        image=Image.open(photo.avatar)
        cropped_image = image.crop((x_value, y_value, width+x_value, height+y_value))
        resized_image = cropped_image.resize((400, 400), Image.ANTIALIAS)
        resized_image.save(photo.avatar.path)

        return photo

apps/auth_accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.shortcuts import render

#django mports
from django.views.generic import FormView, UpdateView

#custom imports
from .forms import UserCreateForm, PhotoForm
from .models import UserProfile
from utils.helpers import LoggedInMixin


class Login(View):
    def get(self, request):
        return render(request, 'login.html')


class SignUp(FormView):
    """
    A form based generic view for user registration
    Takes the user information from and validates the data
    Authenticate the user if form is valid and returns the success url
    """

    form_class = UserCreateForm
    template_name = 'signup.html'

    #form validation and user authentication
    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=raw_password)
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    #return the redirect link after user creation
    def get_success_url(self):
        return reverse('homes:listing')


class UpdateProfile(LoggedInMixin, UpdateView):
    """
    Update view for changing the basic user information
    """
    model = UserProfile
    fields = ['first_name', 'contact_number', 'avatar', ]
    template_name = 'update_profile.html'

    def get_success_url(self):
        return reverse_lazy('homes:my_account', kwargs={'pk': self.object.id})


class ChangeAvatar(UpdateView):
    template_name = 'photo_upload.html'
    model = UserProfile
    form_class = PhotoForm

    # def form_valid(self, form):
    #     form.save()
    #     return super(ChangeAvatar,self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('homes:my_account',kwargs={'pk':self.request.user.id})

apps/auth_accounts/templates/login.html
{% extends 'base_accounts.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
    <h1 class="text-center logo my-4">
      <a href="{% url 'homes:listing' %}">Home Hunter</a>
    </h1>
    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Log in</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Log in</button>
            </form> <!--form closed-->
          </div><!--end of card body-->
          <div class="card-footer text-muted text-center">
            New to Home Hunter? <a href="{% url 'accounts:signup' %}">Sign up</a>
          </div> <!--card footer closed-->
        </div> <!--card  closed-->
        <div class="text-center py-2">
          <small>
            <a href="{% url 'accounts:password_reset' %}" class="text-muted">Forgot your password?</a>
          </small>
        </div> <!--text-center closed-->
      </div> <!--card footer closed-->
    </div> <!--col-lg-4 col-md-6 col-sm-8 closed-->
  </div><!--text-center logo my-4 closed-->
 </div><!--end of container -->
{% endblock %}

apps/auth_accounts/templates/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}



{% block content %}
  <div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12" align="center">
        <div class="col-lg-4 col-md-4 col-sm-4" align="center">
            <div class="card" align="center">
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <button type="submit" class="btn btn-success">Change password</button>
                </form> <!-- form closed-->
          </div> <!-- card closed-->
        </div>  <!---col-lg-4 col-md-4 col-sm-4 -->
    </div> <!--col-lg-12 col-md-12 col-sm-12 -->
  </div><!--row -->
  </div><!--container -->
{% endblock %}

apps/auth_accounts/templates/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
  <li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
  <div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
  </div>
  <a href="{% url 'homes:listing' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

apps/auth_accounts/templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Enter your email address and we will send you a link to reset your password.</p>
          <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/auth_accounts/templates/password_reset_complete.html
{% extends 'base_accounts.html' %}

{% block title %}Password changed!{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Password changed!</h3>
          <div class="alert alert-success" role="alert">
            You have successfully changed your password! You may now proceed to log in.
          </div>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/auth_accounts/templates/password_reset_confirm.html
{% extends 'base_accounts.html' %}

{% block title %}
  {% if validlink %}
    Change password for {{ form.user.username }}
  {% else %}
    Reset your password
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card">
        <div class="card-body">
          {% if validlink %}
            <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
            <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Change password</button>
            </form>
          {% else %}
            <h3 class="card-title">Reset your password</h3>
            <div class="alert alert-danger" role="alert">
              It looks like you clicked on an invalid password reset link. Please try again.
            </div>
            <a href="{% url 'accounts:password_reset' %}" class="btn btn-secondary btn-block">Request a new password reset link</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/auth_accounts/templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
      <div class="card">
        <div class="card-body">
          <h3 class="card-title">Reset your password</h3>
          <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check your spam folder.</p>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to log in</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/auth_accounts/templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The House Hunter Team

apps/auth_accounts/templates/photo_upload.html
{% extends 'base.html' %}

{% block content %}




<link rel="stylesheet" href="{% static 'css/cropper.min.css' %}" >


  <h1 class="page-header"></h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{form}}
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
{#  <div class="row" style="margin-top: 20px">#}
{#    {% for photo in photos %}#}
{#      <div class="col-sm-4 col-md-3">#}
{#        <img src="{{ photo.file.url }}" class="thumbnail">#}
{#      </div>#}
{#    {% endfor %}#}
{#  </div>#}
{##}
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/cropper.min.js' %}"></script>

  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_avatar").change(function () {
          if (this.files && this.files[0]) {
              var reader = new FileReader();
              reader.onload = function (e) {
                  $("#image").attr("src", e.target.result);
                  $("#modalCrop").modal("show");
              }
              reader.readAsDataURL(this.files[0]);
          }

      });
      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
        //debugger;
      var cropBoxData;
      var canvasData;

      $("#modalCrop").on("shown.bs.modal", function () {

        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
          console.log("function called");
        var cropData = $image.cropper("getData");
        $("#id_x_value").val(cropData["x"]);
        $("#id_y_value").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

apps/auth_accounts/templates/signup.html
 {% extends 'base_accounts.html' %}

 {% load static %}

 {% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}


 {% block body %}
  <div class="container">
   <h1 class="text-center logo my-4">
    <a href="#">Home Hunter</a>
   </h1>
   <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card card-inverse card-warning mb-3 text-center">
        <div class="card-body">
          <h3 class="card-title">Sign up</h3>
           <form method="post" novalidate>
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Create an account</button>
           </form>
         </div>
         <div class="card-footer text-muted text-center">
           Already have an account? <a href="{% url 'accounts:login' %}">Log in</a>
         </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

apps/auth_accounts/templates/update_profile.html
{% extends 'base.html' %}





{% block content %}
  <div class="container">

    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title" align="center">Profile Details</h3>
            <form method="post" novalidate enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            </form>
          </div>

        </div>
        <div class="text-center py-2">

        </div>
      </div>
    </div>
  </div>
{% endblock %}