apps/auth_accounts/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    ##-------------Authentication Urls -------------
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    url(r'signup/', SignUp.as_view(),name='signup'),

    ##------------password related urls ----------------
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done'),
        ),
        name='password_reset'),

    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html',
        success_url = reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'),

    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
        ),
        name='password_reset_complete'),

    ##--------------------profile related urls--------------
    url(r'^update_profile/(?P<pk>[\d]+)/$',
        UpdateProfile.as_view(), name='profile_update'),

    url(r'change_avatar/(?P<pk>[\d]+)/$',
        ChangeAvatar.as_view(),
        name='avatar_change')
]

apps/homes/urls.py
from django.conf.urls import url
from .views import *

####---url patterns for calling redirecting to different views with associated namespaces--####

urlpatterns = [
    url(r'^listing/', HomesListing.as_view(), name='listing'),

    url(r'^addcreate', AddCreate.as_view(), name='adcreate'),

    url(r'^homedetail/(?P<slug>[\w-]+)/$', HomeDetail.as_view(),
        name='home_detail'),

    url(r'^update/(?P<slug>[\w-]+)/$', HomeUpdate.as_view(),
        name='home_update'),

    url(r'^like_homes/', LikeHomes.as_view(), name='like_homes'),

    url(r'^favourites/', FavouriteHomes.as_view(),
        name='fav_homes'),

    url(r'^myposts/', MyPosts.as_view(), name='my_posts'),

    url(r'^search/', SearchHomes.as_view(), name='home_search'),

    url(r'^myaccount/(?P<pk>[\w-]+)>', MyAccount.as_view(),
        name='my_account'),

    url(r'makepaymet/(?P<pk>[\d]+)/$', MakePayment.as_view(),
        name='payment'),
]

listinghomes/urls.py
"""
    list of project urls

"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from listinghomes import settings
from apps.homes.views import homelist


urlpatterns = [

    ###########---------------Urls for apps and redirects-----------#########

    url(r'^$', homelist, name="redirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^homes/', include('apps.homes.urls', namespace='homes')),
    url(r'^accounts/', include('apps.auth_accounts.urls', namespace='accounts')),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),




    ###########---------------Urls for password reset and upates-----------#########

    url(r'^settings/password/$',
        auth_views.PasswordChangeView.as_view(
        template_name='password_change.html'),
        name='password_change'),


    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
        name='password_change_done'),
]

 ###########---------------Urls for loading media and static files-----------#########

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/homes/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone

from autoslug import AutoSlugField
from image_cropping import ImageRatioField

class BaseClass(models.Model):

    owner = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Houses(BaseClass):

    slug = AutoSlugField(populate_from='title', unique=True,
                         always_update=True, null=True)
    title = models.CharField(max_length=150)
    adress = models.CharField(max_length=150)
    city = models.CharField(max_length=30)
    postal_code = models.CharField(max_length=30, null=True)
    input_datetime = models.DateTimeField(default=timezone.now)
    expiry_date = models.DateTimeField(default=timezone.now)
    commencement_time = models.DateTimeField(default=timezone.now)
    description = models.CharField(max_length=250, blank=True)
    number_bedrooms = models.CharField(max_length=10, blank=True)
    number_bathrooms = models.CharField(max_length=10, blank=True)
    price = models.FloatField(null=True, blank=True)
    choices = (('s', 'sale'), ('l', 'Rent'))
    sale_type = models.CharField(max_length=20, choices=choices, default='sale')
    tenants = (('b', 'Bachelors'), ('f', 'Family'), ('a', 'Anyone'))
    tenants_type = models.CharField(max_length=20, choices=tenants, default='Anyone')
    house_image = models.ImageField(upload_to='house_images', null=True, blank=True)
    published = models.BooleanField(default=False)
    cropped_image = ImageRatioField('house_image', '430x360')

    class Meta:
        indexes = [
            models.Index(fields=['title', 'city']),
        ]

        verbose_name = "house"
        verbose_name_plural = "houses"

    def __unicode__(self):
        return self.adress

    def get_absolute_url(self):
        return reverse('homes:home_detail', kwargs={'slug': self.slug})

    def is_available(self):
        return self.expiry_date > timezone.now()

    def is_commenced(self):
        return self.commencement_time < timezone.now()


class LikeData(BaseClass):
    house = models.ForeignKey(Houses)

    class Meta:
        verbose_name = "like"
        verbose_name_plural = "likes"

    def __unicode__(self):
        return self.house.title

apps/homes/forms.py
from django.forms import ModelForm
from .models import *



class AddHomeForm(ModelForm):

    class Meta:
        model = Houses
        fields = ['adress', 'city', 'postal_code', 'price', 'sale_type']

apps/homes/views.py
# -*- coding: utf-8 -*-

# future imports
from __future__ import unicode_literals

##django imports
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from utils.helpers import LoggedInMixin, search_homes, complete_payment
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from django.views import View

#custom imports
from .forms import *
import listinghomes.settings as sts

#third party imports
import stripe

#conatsnats and keys
stripe.api_key = sts.STRIPE_SECRET_KEY


class HomesListing(LoginRequiredMixin, ListView):
    """
    A class based view for listing all homes that are published.
    user permission:only logged in users
    """
    model = Houses
    template_name = 'houses_list.html'
    paginate_by = 8

    #queryset for fetching the model data
    def get_queryset(self):
        queryset = Houses.objects.filter(published=True)
        return queryset

homelist = HomesListing.as_view()


class AddCreate(LoggedInMixin, CreateView):

    """
    Generic Createview for creating new Ads.
    Render  CreateForm and validates it,
    user permission:only logged in users
    """
    model = Houses
    fields = ['title', 'adress', 'city', 'price',
              'sale_type', 'description', 'number_bedrooms',
              'number_bathrooms', 'house_image', 'tenants_type']

    template_name = 'houses_form.html'

    #function for validating the form
    def form_valid(self, form):
        new_house = form.save(commit=False)
        new_house.house_image = form.cleaned_data['house_image']
        new_house.owner = self.request.user
        new_house.save()
        return super(AddCreate, self).form_valid(form)

    #returns the url to redirect on successfull object creation
    def get_success_url(self):
        return reverse_lazy('homes:payment', kwargs={'pk': self.object.id})


class HomeDetail(LoggedInMixin, DetailView):
    """
    Generic detailView for returning details associated with each home
    user permission : only logged in users
    Tekes unique Slug value and returns the associated house object
    """
    model = Houses
    template_name = 'house_detail.html'

    #returns the context and any extra data associated with that
    def get_context_data(self, **kwargs):
        context = super(HomeDetail, self).get_context_data(**kwargs)
        context['title'] = 'Home Detail - {}'.format(self.get_object().title)
        return context


class LikeHomes(LoggedInMixin, View):
    """
    A generic view for retruning the like data of a house object by any user
    Takes in house-id and user id and returns if the user has already liked house or not
    Takes in data through ajax requests from detail page of each house object.
    user permission : only logged in users can access this view
    """

    def get(self, request):
        house = get_object_or_404(Houses, id=request.GET.get('house_id'))
        change = int(request.GET.get('state'))
        context = {'status': 0}

        # checks if the user has clicked the like button or not
        if change:
            obj, created = LikeData.objects.get_or_create(
                            owner=request.user,
                            house=house)
            if not created:
                obj.delete()
        #sends a status of 1 if he has already liked, else by default the status is 0.
        if LikeData.objects.filter(owner=self.request.user,
                                   house=house).exists():
                context['status'] = 1

        return JsonResponse(context)


class FavouriteHomes(LoggedInMixin, ListView):
    """
    ListView generic class for displaying the favourite homes of user.
    Returns the homes that are liked by logged-in user
    user permission : only logged in users
    """
    model = LikeData
    template_name = 'favourite_homes.html'

    #Returns the Likedata objects related to loggged in user
    def get_queryset(self):
        queryset = LikeData.objects.filter(owner=self.request.user)
        return queryset


class MyPosts(LoggedInMixin, HomesListing):
    """
    A generic class inherited from HomeListing ListView class
    returns all the ads that are posted by the logged in user
    user permission : only logged in users
    """
    def get_queryset(self):
        queryset = Houses.objects.filter(owner=self.request.user)
        return queryset


class SearchHomes(LoggedInMixin, HomesListing):
    """
    A generic class inherited from HomeListing ListView class
    For searching the homes based on different search queries
    user permission : only logged in users
    """

    #for returning the search results
    def get_queryset(self):
        location = self.request.GET.get('city')
        keyword = self.request.GET.get('keyword')
        home_type = self.request.GET.get('sel-type')
        context_query = search_homes(location, keyword, home_type)
        return context_query

    #returns the context with extra parameters for paginating the search results
    def get_context_data(self, **kwargs):
        context = super(SearchHomes, self).get_context_data(**kwargs)
        context['search'] = True
        context['location'] = self.request.GET.get('city')
        context['keyword'] = self.request.GET.get('keyword')
        context['seltype'] = self.request.GET.get('sel-type')
        return context


class MyAccount(LoggedInMixin, DetailView):
    """
    A generic DetailView for dispalying user details
    Returns both published and pending ads by the user
    user permission : only logged in users
    """

    template_name = 'about.html'
    model = User

    # returns all published and pending homes by the user through context
    def get_context_data(self, **kwargs):
        context = super(MyAccount, self).get_context_data(**kwargs)
        context['homes'] = Houses.objects.filter(owner=self.request.user)
        return context


class HomeUpdate(LoggedInMixin, UpdateView):
    """
    UpdateView for making changes to already added house object.
    Takes the house object through unique slug
    user permission : only logged in users
    Renders a prefilled form with current values of the object.
    """

    model = Houses
    fields = ['title', 'adress', 'city', 'price', 'sale_type',
              'description', 'number_bedrooms',
              'number_bathrooms', 'house_image']

    template_name = 'edit_home_details.html'

    #returns the url to redirect on successfull object updation
    def get_success_url(self):
        return reverse_lazy('homes:home_detail', kwargs={'slug': self.object.slug})


class MakePayment(LoggedInMixin, TemplateView):
    """
    Template view for completing the payment after posting Ads
    Renders a Form for getting the payment details and validates it
    Complete the payment using Stripe payment gateway
    """
    template_name = 'payment.html'

    def get_context_data(self, **kwargs):
        context = super(MakePayment, self).get_context_data(**kwargs)
        context['id'] = self.kwargs['pk']
        context['title'] = 'payment'
        return context

    #getting the payment details from form and completing the payment
    def post(self, request, **kwargs):
        pay = complete_payment(request, kwargs)
        return pay

apps/homes/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumb %}
<a class="navbar-brand"  href="{% url 'homes:listing' %}">All Homes </a>
<a class="navbar-brand"  href="{% url 'homes:fav_homes' %}">My Favourites </a>
<a class="navbar-brand"  href="{% url 'homes:adcreate' %}">New Ad</a>
{% endblock breadcrumb %}


{% block content%}
<div class="container">
    <div class="row">
    <div class="col-sm-2">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card" style="max-height:250px background-color:mintcream;">
                {% if object.userprofile.avatar %}
                <img class="card-img-top" src="{{ object.userprofile.avatar.url }}" alt="Card image cap" style="max-height:100px;">
                {% else %}
                <img class="card-img-top" src="https://diocesedenavirai.org.br/wp-content/uploads/2016/07/default-avatar.png" alt="Card image cap" style="max-height:100px;">
                {% endif %}
                <p align="center"><a href="{% url 'accounts:avatar_change' pk=object.id %}">CHANE AVATAR</a></p>
            </div>
            <div class="card" style="max-height:250px background-color:mintcream;">
            <h3 align="center"> {{ object.username }}</h3>
            <p align="center">{{ object.userprofile.first_name }}</p>
            <p align="center">{{ object.userprofile.contact_number }}</p>
            <p align="center"><a href="{% url 'accounts:profile_update' pk=object.id %}">EDIT</a></p>
            </div>

        </div>
    </div>




 <div class="col-sm-10">
    <div class="col-sm-12">
        <div class="card" style="background-color:gray; ">
            <b class="card-title" align="center">PUBLISHED POSTS</b>
            <div class="w3-row-padding w3-padding-16 w3-center" id="food">
                <div class="table-responsive">
                    <table class="table table-bordered">
                    <thead>
                <tr>

                    <th>Ad Name</th>
                    <th>published on</th>
                    <th>Details</th>
                </tr>
            </thead>
           <tbody>
           {% for home in homes %}
            {% ifequal home.published True %}
            <tr>
                <td>{{home.title}}</td>
                <td>{{home.created_at.date}}</td>
                <td><a href="{% url 'homes:home_detail' slug=home.slug %}">{{ home.title }}</a></td>
            </tr>
             {% endifequal %}
        {% endfor %}
     </tbody>
        </table>
    </div>
</div>
    </div>
   </div>


</br>



    <div class="col-sm-12">
<div class="card" style="background-color:dimgray;">
        <b class="card-title" align="center">PENDING POSTS</b>
         <div class="w3-row-padding w3-padding-16 w3-center" id="food">


        <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>

                    <th>Ad Name</th>
                    <th>published on</th>
                    <th>Details</th>
                </tr>
            </thead>
           <tbody>
           {% for home in homes %}
            {% ifequal home.published False %}
            <tr>
                <td>{{home.title}}</td>
                <td>{{home.created_at.date}}</td>
                <td><a href="{% url 'homes:home_detail' slug=home.slug %}">{{ home.title }}</a></td>
            </tr>
             {% endifequal %}
        {% endfor %}
     </tbody>
        </table>
    </div>
</div>
    </div>
   </div>
</div>
</div>







    </br>
    </br>
    </br>

{% endblock %}

apps/homes/templates/add_home.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'homes:addhome' %}" method="POST" novalidate enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >PROCEED TO PAY $10</button>
</form>
{% endblock %}

apps/homes/templates/edit_home_details.html
{% extends 'base.html' %}





{% block content %}
  <div class="container">

    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title">Edit the Ad</h3>
            <form method="post" novalidate enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-primary btn-block">Confirm</button>
            </form>
          </div>

        </div>
        <div class="text-center py-2">

        </div>
      </div>
    </div>
  </div>
    </br>
    </br>
    </br>
{% endblock %}

apps/homes/templates/favourite_homes.html
{% extends 'base.html' %}


{% block breadcrumb %}
<a class="navbar-brand"  href="{% url 'homes:listing' %}">All Homes </a>
<a class="navbar-brand"  href="{% url 'homes:fav_homes' %}">My Favourites </a>
<a class="navbar-brand"  href="{% url 'homes:adcreate' %}">New Ad</a>
{% endblock breadcrumb %}

{% block content %}
{#<div class="container" style="background-image:'images/home.jpeg'">#}
 <div class="container-fluid">

    <div class="w3-row-padding w3-padding-16 w3-center" id="food">
        {% if object_list %}
        {% for house in object_list %}
        <div class="w3-quarter" style="margin-top:2%;">
            <div class="card" style="max-height:250px; background-color:mintcream;">
                <img class="card-img-top" src="{{ house.house.house_image.url }}" alt="Card image cap" style="max-height:100px;">
{#                    <div class="card-body">#}
                        <h4 class="card-title">{{ house.house.title }}</h4>
                        <p>Location:{{ house.house.city }}</p>
                        <p>Price:{{ house.house.price }}</p>
                        <p><b><a href={% url 'homes:home_detail' slug=house.house.slug %}>See Details</a></b></p>
{#                    </div>#}


             </div>
        </div>

        {% endfor %}

        {% else %}
            <h2>No Favourites yet</h2>
        {% endif %}
</div>
</div>
{% endblock %}

apps/homes/templates/house_detail.html
{% extends 'base.html' %}
{% block breadcrumb %}
<a class="navbar-brand"  href="{% url 'homes:listing' %}">All Homes </a>
<a class="navbar-brand"  href="{% url 'homes:fav_homes' %}">My Favourites </a>
<a class="navbar-brand"  href="{% url 'homes:adcreate' %}">New Ad</a>
{% endblock breadcrumb %}


{% block content%}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">



<div class="container">
<div class="row">
    <div class="col-lg-8 col-sm-8 col-md-8">
    <div class="w3-row-padding w3-padding-16">
        {% if object.house_image %}
                <img src="{{ object.house_image.url }}" height="80%" width="80%">
        {% else %}
                <img src="http://customerengagement.asia/Blog/img/no_img.png" height="80%" width="80%">
        {% endif %}
        </div>
       </div>

        <div class="col-lg-4 col-sm-4 col-md-4">
            <h2>{{ object.title }}</h2>
            <div class="col-sm-12">
                <p><b>City</b> : {{ object.city }}</p>
                <p><b>Price</b> : {{ object.price }}</p>
                <p><b>address</b> : {{ object.adress }}</p>
                <p><b>Bedrooms</b> : {{ object.number_bedrooms }}</p>
                <p><b>Bathrooms</b> : {{ object.number_bathrooms }}</p>
                <p><b>Type</b> : {{ object.get_sale_type_display }}</p>
                <p><b>contact</b> : {{ object.owner.userprofile.contact_number }}</p>
                <p><b>Poted By</b> : {{ object.owner.userprofile.first_name }}</p>
                <p><b>Poted On</b> : {{ object.updated_at.date}}</p>
                <p><b>Prefered Tenants</b> : {{ object.tenants_type_display}}</p>
              </div>
        </div>
    </div>


{% ifequal object.owner request.user %}
    <p><b>Payment:</b> {{ object.published|yesno:"success,pending" }}</p>

<p><a href={% url 'homes:home_update' slug=object.slug %}>EDIT CONTENTS</a></p>

    {% if not object.published  %}
        <p><a href={% url 'homes:payment' pk=object.id %}>Publish</a></p>

    {% endif %}



{% else %}

<button id="like" type="button" class="btn btn-success" data-url="{% url 'homes:like_homes' %}" data-id="{{ object.id }}">LIKE</button>
{% endifequal %}



</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script>
$(document).ready(function()
{
    var data_url = $("#like").attr('data-url');
    var data_id = $("#like").attr('data-id');
    ajaxcall(data_url, data_id,0);

    function ajaxcall(data_url, data_id, state) {

        $.ajax({
            type: 'GET',
            dataType: 'json',
            url: data_url,
            data: {house_id: data_id, state:state}
        }).then(function (resp) {
            if (resp.status) {
                $("#like").text('UNLIKE');

            }
            else {
                $("#like").text('LIKE');
            }
        }, function (jqXHR, textStatus, errorThrown) {
            console.log(jqXHR.status);
            console.log(textStatus);
            console.log(errorThrown);
        });
    }

    $(document).on('click', "#like", function(){
        ajaxcall($(this).attr('data-url'), $(this).attr('data-id'), 1);
    });


});
</script>


{% endblock %}

apps/homes/templates/houses_form.html
{% extends 'base.html' %}

{% load static %}

{% block breadcrumb %}
<a class="navbar-brand"  href="{% url 'homes:listing' %}">All Homes </a>
<a class="navbar-brand"  href="{% url 'homes:fav_homes' %}">My Favourites </a>
<a class="navbar-brand"  href="{% url 'homes:adcreate' %}">New Ad</a>
{% endblock breadcrumb %}

{% block content %}
  <div class="container">

    <div class="row justify-content-center">
      <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
          <div class="card-body">
            <h3 class="card-title" align="center">Post New Ad</h3>
            <form method="post" novalidate enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'includes/form.html' %}
              <button type="submit" class="btn btn-success btn-block">Proceed to Pay $10</button>
            </form>
          </div>

        </div>
        <div class="text-center py-2">

        </div>
      </div>
    </div>
  </div>
    </br>
    </br>
    </br>

{% endblock %}

apps/homes/templates/houses_list.html
{% extends 'base.html' %}
{% load cropping %}
{% block breadcrumb %}
<a class="navbar-brand"  href="{% url 'homes:listing' %}">All Homes </a>
<a class="navbar-brand"  href="{% url 'homes:fav_homes' %}">My Favourites </a>
<a class="navbar-brand"  href="{% url 'homes:adcreate' %}">New Ad</a>

 <div class="navbar-brand">
    <form class="navbar-form" role="search" action="{% url 'homes:home_search' %}" method="get">

        <div class="input-group">
            <input type="text" class="form-control" placeholder="city" name="city" id="city" value="{{ location }}">
            <input type="text" class="form-control" placeholder="keyword" name="keyword" id="keyword" value="{{ keyword }}">
            <select name="sel-type" id="sel-type">
                <option value="both">BOTH</option>
                <option value="s">SALE</option>
                <option value="l">RENT</option>
             </select>
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>Search</button>
            </div>
        </div>
    </form>
</div>

{% endblock breadcrumb %}








{% block content %}
{#<div class="container" style="background-image:'images/home.jpeg'">#}
 <div class="container-fluid">
    <div class="w3-row-padding w3-padding-16 w3-center" id="food">
       {% if object_list %}
            {% for house in object_list %}
                <div class="w3-quarter" style="margin-top:2%;">
                    <div class="card" style="max-height:250px; background-color:mintcream;">
                        {% if house.house_image %}
                        <img class="card-img-top"  src="{% cropped_thumbnail house "cropped_image" scale=0.25 %} alt="Card image cap" style="max-height:100px;">
                        {% else %}
                        <img class="card-img-top" src="http://customerengagement.asia/Blog/img/no_img.png" alt="Card image cap" style="max-height:100px;">
                        {% endif %}
{#                    <div class="card-body">#}
                        <h4 class="card-title">{{ house.title }}</h4>
                        <p>Location:{{ house.city }}</p>
                        <p>Price:{{ house.price }}</p>
                        <p><b><a href={% url 'homes:home_detail' slug=house.slug %}>See Details</a></b></p>
{#                    </div>#}
                    </div>
                </div>
            {% endfor %}
           </div>
      {% else %}
      <h3>No results Found</h3>
      {% endif %}



 {% if not search %}
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}" class="w3-bar-item w3-button w3-hover-black">«</a>
      {% endif %}

      <a href="#" class="w3-bar-item w3-button "> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>


    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}" class="w3-bar-item w3-button w3-hover-black">»</a>
    {% endif %}
    </div>
  </div>
{% endif %}

 {% if search %}
<div class="w3-center w3-padding-32">
    <div class="w3-bar">
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}&city={{ location }}&sel-type={{ seltype }}&keyword={{ keyword }}" class="w3-bar-item w3-button w3-hover-black">«</a>
      {% endif %}

      <a href="#" class="w3-bar-item w3-button "> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a>


    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}&city={{ location }}&sel-type={{ seltype }}&keyword={{ keyword }}" class="w3-bar-item w3-button w3-hover-black">»</a>
    {% endif %}
    </div>
  </div>
 {% endif %}
</div>
{% endblock %}

apps/homes/templates/user_form.html
<html>
<head></head>
<body>
<form action=" " method="POST" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" >ADD</button>
</form>
</body>
</html>