apps/auth_accounts/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    ##-------------Authentication Urls -------------
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    url(r'signup/', SignUp.as_view(),name='signup'),

    ##------------password related urls ----------------
    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.html',
        subject_template_name='password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done'),
        ),
        name='password_reset'),

    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html',
        success_url = reverse_lazy('accounts:password_reset_complete'),
        ),
        name='password_reset_confirm'),

    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'
        ),
        name='password_reset_complete'),

    ##--------------------profile related urls--------------
    url(r'^update_profile/(?P<pk>[\d]+)/$',
        UpdateProfile.as_view(), name='profile_update'),

    url(r'change_avatar/(?P<pk>[\d]+)/$',
        ChangeAvatar.as_view(),
        name='avatar_change')
]

apps/homes/urls.py
from django.conf.urls import url
from .views import *

####---url patterns for calling redirecting to different views with associated namespaces--####

urlpatterns = [
    url(r'^listing/', HomesListing.as_view(), name='listing'),

    url(r'^addcreate', AddCreate.as_view(), name='adcreate'),

    url(r'^homedetail/(?P<slug>[\w-]+)/$', HomeDetail.as_view(),
        name='home_detail'),

    url(r'^update/(?P<slug>[\w-]+)/$', HomeUpdate.as_view(),
        name='home_update'),

    url(r'^like_homes/', LikeHomes.as_view(), name='like_homes'),

    url(r'^favourites/', FavouriteHomes.as_view(),
        name='fav_homes'),

    url(r'^myposts/', MyPosts.as_view(), name='my_posts'),

    url(r'^search/', SearchHomes.as_view(), name='home_search'),

    url(r'^myaccount/(?P<pk>[\w-]+)>', MyAccount.as_view(),
        name='my_account'),

    url(r'makepaymet/(?P<pk>[\d]+)/$', MakePayment.as_view(),
        name='payment'),
]

listinghomes/urls.py
"""
    list of project urls

"""
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from listinghomes import settings
from apps.homes.views import homelist


urlpatterns = [

    ###########---------------Urls for apps and redirects-----------#########

    url(r'^$', homelist, name="redirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^homes/', include('apps.homes.urls', namespace='homes')),
    url(r'^accounts/', include('apps.auth_accounts.urls', namespace='accounts')),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),




    ###########---------------Urls for password reset and upates-----------#########

    url(r'^settings/password/$',
        auth_views.PasswordChangeView.as_view(
        template_name='password_change.html'),
        name='password_change'),


    url(r'^settings/password/done/$',
        auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
        name='password_change_done'),
]

 ###########---------------Urls for loading media and static files-----------#########

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
      <title img scr="http://icons.iconarchive.com/icons/fps.hu/free-christmas-flat-circle/512/home-icon.png">{% block title %}Home Hunter{% endblock %}</title>
      <link rel="stylesheet" href="{% static 'css/static.css' %}">
      <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"
      <link rel="stylesheet" href="{% static 'css/app.css' %}">
      <link rel="stylesheet" href="{% static 'css/footer.css' %}">
      <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    {% block stylesheet %}{% endblock %}

  </head>
  <body>
    {% block body %}
   <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand"  href="{% url 'homes:listing' %}">Home Hunter </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="mainMenu">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
            <a class="dropdown-item" href="{% url 'homes:my_account' pk=request.user.id %}">My account</a>
            <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </div>
        </li>
      </ul>
        {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'accounts:login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
      {% endif %}

    </div>
  </div>
</nav>

    <div class="container" style="">
      <ol class="breadcrumb my-4">
        {% block breadcrumb %}

        {% endblock %}
      </ol>
      {% block content %}
      {% endblock %}
    </div>

  {% block footer %}
            <div class="footer navbar navbar-expand-sm navbar-dark bg-dark">
            <div class="footercenter">
            <p >&copy; 2017 -  Home Hunter International </p>
            </div>
            </div>
  {% endblock %}

    {% endblock body %}
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/cropper.min.js' %}"></script>


  </body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
  <div class="container">
        <h1 class="text-center logo my-4">
        <a href="{% url 'homes:listing' %}">Django Boards</a>
        </h1>
    {% block content %}
    {% endblock %}
  </div>
{% endblock %}

templates/error.html
{% extends 'base.html' %}

{% block content %}
<div align="center">
<h2>something went wrong!</h2>
 <p>try again</p>
<p>error:{{ error }}</p>
</div>
{% endblock %}

templates/success.html
{% extends 'base.html' %}
{{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class ="col-sm-4 col-md-4 col-lg-4 " >

            <div class="card" style=" ">


                {% comment %}
                used a extrnal image url since heroku deletes static images
                {% endcomment %}
                <br/>
            <img class="card-img-top" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Yes_Check_Circle.svg/480px-Yes_Check_Circle.svg.png" style="max-height:100px;width:100px; align-self:center;">


           <div class="justify-content-center success_center">

           <h2>Payment Successful </h2>
               </br>

           <p><b>REFRENCE_ID</b>
           <p>{{ charge.id }}</p>
               </br>

           <p><b>Amount</b>
           <p>${% widthratio charge.amount 100 1 %} </p>

           <p><b>From Account</b>
           <p>XXXX-XXXX-XXXX-{{ charge.source.last4 }} </p>

           <p><button class="btn btn-success" align="center" type="button" value="Continue" onclick="location.href='{% url 'homes:home_update' slug=slug %}'">Continue</button>
            </p></div>
            </div>
        </div>
     </div>
</div>
    </br>
    </br>
{% endblock %}

templates/test.html
<form class="navbar-form" role="search" action="{% url 'homes:home_search' %}" method="get">
    {% csrf_token %}
    <div class="input-group">
        <input type="text" class="form-control" placeholder="city" name="city" id="city">
        <input type="text" class="form-control" placeholder="keyword" name="keyword" id="keyword">
    <div class="input-group-btn">
      <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>Search</button>